upstream tdo_be {
  server node:9999;
}

upstream tdo_fe {
  server react:3000;
}

server {
  listen 80;

  location /tdo_be {
    rewrite /tdo_be/(.*) /$1 break;
    proxy_pass http://tdo_be;
  }

  location / {
    proxy_pass http://tdo_fe;
  }
}