const SUCCESS_CODE = 200;
const VALIDATION_FAIL_CODE = 400;
const AUTHENTICATION_FAIL_CODE = 401;
const NOT_ALLOW_CODE = 403;
const NOT_FOUND_CODE = 404;
const ERROR_EXCEPTION_CODE = 500;

module.exports = { SUCCESS_CODE, VALIDATION_FAIL_CODE, AUTHENTICATION_FAIL_CODE, NOT_ALLOW_CODE, NOT_FOUND_CODE, ERROR_EXCEPTION_CODE };
